---
# General
- name: Update RedHat system
  block:
    - name: Update system
      become: true
      dnf:
        name: "*"
        state: latest

    - name: Install base packages
      become: true
      dnf:
        name: "{{ packages }}"
        state: latest
  when: ansible_os_family == "RedHat"

- name: Update Debian system
  block:
    - name: Update system
      become: true
      apt:
        name: "*"
        state: latest

    - name: Install base packages
      become: true
      apt:
        name: "{{ packages }}"
        state: latest
  when: ansible_os_family == "Debian"

- name: Populate service facts
  service_facts:

- name: Install grafana
  import_tasks: grafana.yml

- name: Install prometheus
  import_tasks: prometheus.yml

- name: Install node_exporter
  import_tasks: node_exporter.yml

- name: Install loki
  import_tasks: loki.yml

- name: Install Promtail
  import_tasks: promtail.yml