---
# Handlers
- name: Restart Grafana
  service:
    name: grafana-server
    enabled: yes
    state: restarted

- name: Restart Prometheus
  service:
    name: prometheus
    enabled: yes
    state: restarted

- name: Restart Node_exporter
  service:
    name: node_exporter
    enabled: yes
    state: restarted

- name: Restart Loki
  service:
    name: loki
    enabled: yes
    state: restarted

- name: Restart Promtail
  service:
    name: promtail
    enabled: yes
    state: restarted

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded